apiVersion: apps/v1
kind: Deployment
metadata:
  name: lukasgermerott-de-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: germerott
  template:
    metadata:
      labels:
        app: germerott
    spec:
      containers:
      - name: lukasgermerott
        image: lukasgerm/lukasgermerott-de:1.2.3
        imagePullPolicy: Always
        env:
        - name: GOOGLE_ANALYTICS_CODE
          value: "UA-167972589-2"
        - name: LANGUAGE
          value: "de"
        - name: FEATURE_BLOG
          value: "false"
        - name: TURNSTILE_SITE_KEY
          value: "SITE_KEY"
        - name: TURNSTILE_SECRET
          value: "SECRET"
        - name: SENDGRID_KEY
          value: "SENDGRID_KEY"
---
apiVersion: v1
kind: Service
metadata: 
  name: lukasgermerott-de-service
spec:
  type: NodePort
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31324
  selector:
    app: germerott
