version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  install:
    docker:
      - image: "cimg/node:18.12.1"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test_unit:
    docker:
      - image: "cimg/node:18.12.1"
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test:unit
workflows:
  lukasgermerott:
    jobs:
      - install
      - test_unit:
          requires:
            - install