# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: circleci/node@4.7
    steps:
      - run:
          name: Build application
          command: yarn run build
  test_unit:
    docker:
      - image: circleci/node@4.7
    steps:
      - run:
          name: Test
          command: yarn run test:unit
  test_e2e:
    docker:
      - image: circleci/node@4.7
    steps:
      - run:
          name: Test
          command: yarn run test:e2e


